#!/bin/bash

echo "Checking if python exists"
if command -v python3 > /dev/null 2>&1; then
    py=$(which python3)
    echo "Using python3"
else
    if python --version | grep -q "3."; then
        py=$(which python)
        echo "Using python"
    else
        echo "Please install Python3 or 3.11 manually."
        exit 1
    fi
fi

# Detect the current directory and activate the virtual environment
VENV_DIR="$PWD/venv"
if [ -d "$VENV_DIR" ]; then
    echo "Activating virtual environment in $VENV_DIR"
    source "$VENV_DIR/bin/activate"
else
    echo "Virtual environment not found in $VENV_DIR"
    exit 1
fi

# Execute your Python script
$py chzzk_record.py

exit 0

