#!/bin/bash

echo "필수 구성 요소를 설치합니다"
python -m venv venv
source venv/bin/activate
pip install requests streamlink
deactivate
echo "필수 구성요소 설치가 완료되었습니다!"

ehco "채널 설정을 시작합니다"
bash "채널 설정"
echo "설정이 완료 되었습니다!"
echo "채널 설정을 다시 하고 싶으면 \"채널 설정\" 스크립트를 직접 실행하세요"
exit 0
