#!/bin/bash

echo "Checking if Python exists"
# Check for Python 3 and assign its path to a variable
if command -v python3 > /dev/null 2>&1; then
    py=$(which python3)
    echo "Using python3"
else
    if python --version 2>&1 | grep -q '3.'; then
        py=$(which python)
        echo "Using python"
    else
        echo "Please install Python3 or 3.11 manually."
        exit 1
    fi
fi

echo "Installing required components"
# Create a virtual environment in the current directory
$py -m venv venv

# Dynamically get the current directory's virtual environment activation script
VENV_DIR="$PWD/venv"
if [ -d "$VENV_DIR" ]; then
    echo "Activating virtual environment in $VENV_DIR"
    source "$VENV_DIR/bin/activate"
else
    echo "Virtual environment not found in $VENV_DIR"
    exit 1
fi

# Install required Python packages
"$VENV_DIR/bin/pip" install --upgrade streamlink aiohttp aiofiles orjson

# Deactivate the virtual environment
deactivate
echo "Required components installation completed!"

echo "Downloading chzzk.py plugin"
# Create plugin directory if it doesn't exist
PLUGIN_DIR="$PWD/plugin"
mkdir -p "$PLUGIN_DIR"

# Plugin URL
PLUGIN_URL="https://raw.githubusercontent.com/fml09/streamlink/c29ab4040b56511b4fd4915954b8b0796b72ad40/src/streamlink/plugins/chzzk.py"
PLUGIN_FILE="$PLUGIN_DIR/chzzk.py"

# Download and update plugin if necessary
if [ -f "$PLUGIN_FILE" ]; then
    # Download file to a temporary location
    TMP_FILE=$(mktemp)
    wget -q -O "$TMP_FILE" "$PLUGIN_URL"
    
    # Check if the existing file is different from the new download
    if ! cmp -s "$TMP_FILE" "$PLUGIN_FILE"; then
        echo "Updating chzzk.py plugin"
        mv "$TMP_FILE" "$PLUGIN_FILE"
    else
        echo "chzzk.py is up to date"
        rm "$TMP_FILE"
    fi
else
    echo "Downloading chzzk.py plugin"
    wget -q -O "$PLUGIN_FILE" "$PLUGIN_URL"
fi

echo "Starting configuration"
# Execute the settings script
bash settings
echo "Configuration completed!"
echo "If you want to reconfigure, please run the \"settings\" script directly"

exit 0
