#!/bin/bash

# Termux 환경에서는 $py 대신 python 사용
if [[ -n $(command -v termux-setup-storage) ]]; then
    echo "Termux 환경입니다."
    source venv/bin/activate
    python settings.py
    exit 0
else
    echo "일반적인 리눅스 환경입니다."
    if command -v python3 > /dev/null 2>&1; then
        py=$(which python3)
        echo "Using python3"
    else
        if python --version | grep -q 3.; then
            py=$(which python)
            echo "Using python"
        else
            echo "Please install Python3 or 3.11 manually."
            exit 1
        fi
    fi
    
    source venv/bin/activate
    $py settings.py
    
    exit 0
fi

